skp_olist_data_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: <Project_ID>
      dataset: olist
      location: US
      threads: 4
      keyfile: <Path to GCP Project Service Account JSON>
      timeout_seconds: 300
  
