version: 2

sources:
  - name: staging
    database:  trans-array-412413
    schema: olist
    
    tables:
      - name: olist_customers_dataset

      - name: olist_orders_dataset

      - name: olist_order_items_dataset

      - name: olist_products_dataset

      - name: product_category_name_translation

      - name: olist_sellers_dataset

      - name: olist_order_payments_dataset


