version: 2

sources:
  - name: staging
    database:  <Project ID>
    schema: <Schema ID>
    
    tables:
      - name: CustomerLifeTimeOrderCount_View

      - name: customersandorders

      - name: sellersproductsinorders

      - name: CustomersTotalPaymentsValue


version: 2

models:
  - name: sellersproductsinorders
    description: ""
    columns:
      - name: order_id
        data_type: string
        description: ""

      - name: orderpurchaseddate
        data_type: timestamp
        description: ""

      - name: order_item_id
        data_type: int64
        description: ""

      - name: seller_id
        data_type: string
        description: ""

      - name: product_id
        data_type: string
        description: ""

      - name: product_category_name
        data_type: string
        description: ""

      - name: product_category_name_english
        data_type: string
        description: ""

  - name: customersandorders
    description: ""
    columns:
      - name: customer_unique_id
        data_type: string
        description: ""

      - name: customer_id
        data_type: string
        description: ""

      - name: order_id
        data_type: string
        description: ""

      - name: orderpurchaseddate
        data_type: timestamp
        description: ""

  - name: customerstotalpaymentsvalue
    description: ""
    columns:
      - name: customer_unique_id
        data_type: string
        description: ""

      - name: sum
        data_type: float64
        description: ""

  - name: customerlifetimeordercount_view
    description: ""
    columns:
      - name: totalorders
        data_type: int64
        description: ""

      - name: customerscount
        data_type: int64
        description: ""
